### ISSUE TITLE
Ошибка в работе кнопки местоположения заведения 

### ISSUE THREAD

**Issue by DimaShul** [Ace-Place/bug-tracker#124]
**Описание бага**
Если перейти в заведение через карту, нажав на иконку, затем пролистнуть вниз и нажать на кнопку местоположение, то реакции приложения нет.

**Ожидаемое поведение (Опционально)**
По-моему мнению, данная кнопка, то есть ее функция должна выполняться. К тому же на прошлых версиях приложения кнопка работала.

**Медиа (Опционально)**

https://user-images.githubusercontent.com/89010091/143664332-1cbd9163-369f-4463-922a-963e946e8560.MP4

Сведения об устройстве:
 - Устройство: UMIDIGI A9 Pro
 - OS: Android 11
 - Версия приложения 2.1.7

**Comment by yulia2012394** [comment]
Не вижу смысла в этой функции тут, тк нелогично из карты снова переходить в карту.
