### ISSUE TITLE
Ошибка в списке подписок + жалоба

### ISSUE THREAD

**Issue by DimaShul** [Ace-Place/bug-tracker#168]
**Описание бага**
Если в первую очередь кинуть жалобу, но затем подписаться на заведение и перейти в список подписок, то четко видно, что данное заведение отображается в конце списка подписок.

**Ожидаемое поведение (Опционально)**
Мне кажется, что стоит пересмотреть данную функцию и конкретно определиться с жалобой и размещением заведения в списке подписок.

**Медиа (Опционально)**

https://user-images.githubusercontent.com/89010091/147601194-38eb597a-6ae4-4781-9eaa-5ca6fe304fbf.MP4

Сведения об устройстве:
 - Устройство:  iPhone Хs max
 - OS: iOS 15.1
 - Версия приложения 4.1.1

**Comment by ReanSn0w** [comment]
closed in 504
