### ISSUE TITLE
Помарка с кнопкой местоположения 

### ISSUE THREAD

**Issue by DimaShul** [Ace-Place/bug-tracker#171]
**Описание бага**
Помарка заключается в том, что кнопка пикается вместе с акцией.

**Ожидаемое поведение (Опционально)**
Как мне кажется было бы лучше, если бы кнопка местоположения нажималась отдельно на акции, а не вместе со всей акцией.

**Медиа (Опционально)**

https://user-images.githubusercontent.com/89010091/148098299-8a70d00b-2d10-453c-9f5d-bcb47f4ecaf3.MP4

Сведения об устройстве:
 - Устройство:  iPhone 12
 - OS: iOS 15.1.1
 - Версия приложения 4.1.1

**Comment by ReanSn0w** [comment]
fixed in 502
