### ISSUE TITLE
Ошибка с выбором фильтра

### ISSUE THREAD

**Issue by DimaShul** [Ace-Place/bug-tracker#180]
**Описание бага**
После того как через фильтр выбрал пункт (образование), на карте появляется одна единственная иконка с каруселью, как мне кажется, это явно не раздел образования.

**Ожидаемое поведение (Опционально)**
По заведению и его акции четко видно, что тематика не соответствует иконке ( заведению), стоит пересмотреть функции фильтров и их корректность при отображении заведения на карте.

**Медиа (Опционально)**

https://user-images.githubusercontent.com/89010091/149430385-ead1c1b1-78b4-48c9-a9ff-0d6e7123f230.MP4

Сведения об устройстве:
 - Устройство:  iPhone 12
 - OS: iOS 15.1.1
 - Версия приложения 4.1.1

**Comment by ReanSn0w** [comment]
fix icons in 502
