### ISSUE TITLE
Ошибка при нажатие на кнопку закрыть ❌

### ISSUE THREAD

**Issue by DimaShul** [Ace-Place/bug-tracker#182]
**Описание бага**
Ошибка в том, что при нажатии на кнопку закрыть в правом верхнем углу не происходит никакой реакции, не получается вернуться на карту.

**Ожидаемое поведение (Опционально)**
Стоит пересмотреть работу кнопки закрыть✖️

**Медиа (Опционально)**
https://user-images.githubusercontent.com/89010091/149600030-19fe4a41-3a1c-4f20-9a89-39050ed70431.MP4

Сведения об устройстве:
 - Устройство:  iPhone 12
 - OS: iOS 15.1.1
 - Версия приложения 4.1.1

**Comment by ReanSn0w** [comment]
closed in 503
