### ISSUE TITLE
Ошибка ссылкой на новость

### ISSUE THREAD

**Issue by DimaShul** [Ace-Place/bug-tracker#184]
**Описание бага**
Ошибка заключается в том, что если скинуть две ссылки через разные варианты, то одна ссылка корректна (та что через верхние три точки), а вот если через стрелку (кнопка поделиться), то отправляется ссылка на приложение, а не на саму новость

**Ожидаемое поведение (Опционально)**
Стоит рассмотреть работу ссылки через кнопку поделиться у новости, там где комментарии.

**Медиа (Опционально)**
Отправил в лс в тг.

Сведения об устройстве:
 - Устройство:  iPhone 12
 - OS: iOS 15.1.1
 - Версия приложения 4.1.1

**Comment by ReanSn0w** [comment]
closed in 503
