### ISSUE TITLE
Проблема с уменьшением карты

### ISSUE THREAD

**Issue by DimaShul** [Ace-Place/bug-tracker#206]
**Описание бага**
При резком нажатии на «-», то есть уменьшение карты, происходит торможение изображения.

**Ожидаемое поведение (Опционально)**
Стоит рассмотреть данную функцию, возможно попробовать как-то изменить ее.

**Медиа (Опционально)**

https://user-images.githubusercontent.com/89010091/151659994-f0e31ac7-e372-4c0d-abaf-8844016f9d74.MP4

Сведения об устройстве:
 - Устройство:  iPhone 12
 - OS: iOS 15.1.1
 - Версия приложения 5.1.0 (514)

**Comment by ReanSn0w** [comment]
На загрузку карты требуется время, тут ничего не поделать.
