### ISSUE TITLE
Проблема с кошелком

### ISSUE THREAD

**Issue by DimaShul** [Ace-Place/bug-tracker#214]
**Описание бага**
Ошибка в том, что после сканирования qr-кода, приложение не считает место оцененным, при нажатии на кнопку готово при прошлом отзыве.

**Ожидаемое поведение (Опционально)**
По-моему мнению, должна быть возможность еще раз написать допустим новый отзыв о заведение, а не подтверждать прошлый.

**Медиа (Опционально)**
Отправил в тг (02.02.2022.)

Сведения об устройстве:
 - Устройство:  iPhone 12
 - OS: iOS 15.1.1
 - Версия приложения 5.1.0 (515)

**Comment by ReanSn0w** [comment]
TODO: - перепроверить форму для review
