### ISSUE TITLE
Проблема с авторизацией аккаунта

### ISSUE THREAD

**Issue by DimaShul** [Ace-Place/bug-tracker#237]
**Описание бага**
Проблема заключается в том, что после авторизации полностью нового аккаунта, в избранных остаются акции с прошлого акка.

**Ожидаемое поведение (Опционально)**
Аккаунт полностью новый, следовательно и подписок и списка избранных акций быть не должно.

**Медиа (Опционально)**

https://user-images.githubusercontent.com/89010091/155001474-2d214ef7-ab32-4562-947b-fbaca7e07d82.MP4

Сведения об устройстве:
 - Устройство: Redmi Note 8 Pro
 - OS: Android 10 QP1A. 190711. 020
 - Версия приложения 2.2.0

**Comment by yulia2012394** [comment]
Всё работает, такого бага нет.
