### ISSUE TITLE
Проблема с qr кодом

### ISSUE THREAD

**Issue by DimaShul** [Ace-Place/bug-tracker#241]
**Описание бага**
Нет плавно перехода, когда выходишь с qr кода.

**Ожидаемое поведение (Опционально)**
По-моему мнению, стоит рассмотреть данную функцию, она должна работать без тормоза и тд.

**Медиа (Опционально)**

https://user-images.githubusercontent.com/89010091/155361924-67850a45-f265-483e-baa3-a70a80ad06cd.mov

Сведения об устройстве:
 - Устройство: Redmi Note 8 Pro
 - OS: Android 10 QP1A. 190711. 020
 - Версия приложения 2.2.0

**Comment by yulia2012394** [comment]
Так работает zxing API, тут также сделать ничего нельзя.
