### ISSUE TITLE
Проблема с отзывом при сканировании qr кода

### ISSUE THREAD

**Issue by DimaShul** [Ace-Place/bug-tracker#245]
**Описание бага**
Проблема заключается в том, что нет возможности после сканирования qr кода, опубликовать отзыв.

**Ожидаемое поведение (Опционально)**
Должна быть возможность опубликовать отзыв через qr код.

**Медиа (Опционально)**

https://user-images.githubusercontent.com/89010091/155881739-dd9defba-2fc0-44eb-8c6c-1bd817443aea.mov

Сведения об устройстве:
 - Устройство: Redmi Note 8 Pro
 - OS: Android 10 QP1A. 190711. 020
 - Версия приложения 2.2.0

**Comment by yulia2012394** [comment]
Ошибка была на бэкенде.
