### ISSUE TITLE
Помарка в изменение масштаба карты

### ISSUE THREAD

**Issue by DimaShul** [Ace-Place/bug-tracker#246]
**Описание бага**
В момент увеличения или же уменьшения карты, видно как карта не успевает про грузиться, бывали ситуации во время тестирования, что больше времени требовалось на подгрузку карты. 

**Ожидаемое поведение (Опционально)**
В момент пользования приложением, по-моему мнению у пользователя не должно возникать данной проблемы.

**Медиа (Опционально)**

https://user-images.githubusercontent.com/89010091/156339955-c6fe72a6-4e4f-48b2-b178-44ab492c20cf.mov

Сведения об устройстве:
 - Устройство: Redmi Note 8 Pro
 - OS: Android 10 QP1A. 190711. 020
 - Версия приложения 2.2.0

**Comment by yulia2012394** [comment]
Так работает Google Maps API и с этим, к сожалению, ничего не поделать.
