### ISSUE TITLE
Проблема с вопросами к акции

### ISSUE THREAD

**Issue by DimaShul** [Ace-Place/bug-tracker#251]
**Описание бага**
Проблема при счете количества вопросов к акции, проблема заключается в том, что при публикации вопроса он не сразу засчитывается.

**Ожидаемое поведение (Опционально)**
Необходимо, сначала перейти в другой раздел, чтобы обновились вопросы и только тогда, но опять же не всегда появляется счет вопросов.
Как мне кажется, стоит сделать, так чтобы после нажатия на кнопку «отправить» сразу засчитывался вопрос.

**Медиа (Опционально)**

https://user-images.githubusercontent.com/89010091/157048842-1bd916d3-2213-4fa6-bd1d-e60d9aad80dc.mov

Сведения об устройстве:
 - Устройство: Redmi Note 8 Pro
 - OS: Android 10 QP1A. 190711. 020
 - Версия приложения 2.2.0

**Comment by yulia2012394** [comment]
Исправлено в прошлых багах.
