### ISSUE TITLE
Ошибка в функции 

### ISSUE THREAD

**Issue by DimaShul** [Ace-Place/bug-tracker#51]
**Описание бага**
Не работает кнопка трех точек(…) в разделе подписки 

**Ожидаемое поведение (Опционально)**
По-моему мнению функция трех точек должна работать или же нет смысла ставить три точки.

**Медиа (Опционально)**

https://user-images.githubusercontent.com/89010091/138138964-71078d82-e76f-4d8d-9746-c62a67eff4ad.MP4

 

**Сведения об устройстве:**
 - Устройство: iPhone Хs max
 - OS: iOS14.7.1
 - Версия приложения 4.0.0

**Comment by ReanSn0w** [comment]
исправлено в релизе, которой идет на публикацию сегодня
