### ISSUE TITLE
Небольшая помарка в момент добавления в избранное

### ISSUE THREAD

**Issue by DimaShul** [Ace-Place/bug-tracker#52]
**Описание бага**
Когда в момент добавления акции в избранное  с помощью сердечка, при нажатии на него моргает вся картинка.

**Ожидаемое поведение (Опционально)**
Как мне кажется, если бы только сердечко загоралось было бы на много лучше и приятнее видеть пользователю.

**Медиа (Опционально)**

https://user-images.githubusercontent.com/89010091/138139542-16076886-e251-48b1-a30a-6aa6d9910118.MP4

**Сведения об устройстве:**
 - Устройство: iPhone Хs max
 - OS:  iOS14.7.1
 - Версия приложения 4.0.0

**Comment by ReanSn0w** [comment]
issue перенесен из разряда багов в разред улучшений
