### ISSUE TITLE
Не получается нажать на кнопку коментов

### ISSUE THREAD

**Issue by DimaShul** [Ace-Place/bug-tracker#65]
**Описание бага**
Не получается нажать на кнопку комментариев, обычно при нажатии на эту кнопку выплывает возможность сразу писать комент на клавиатуре.

**Ожидаемое поведение (Опционально)**
По-моему мнению, если такая кнопка имеется она должна работать.

**Медиа (Опционально)**

https://user-images.githubusercontent.com/89010091/138753380-cddc8c32-9971-4f55-9846-747e6b3f2e07.mov

 

![9C1216F7-DC0E-49F2-BF7E-A797FA257483](https://user-images.githubusercontent.com/89010091/138753396-d14b830f-88e7-4bc8-a04a-16b8f1716f92.jpeg)

Сведения об устройстве:
 - Устройство:  iPhone Хs max
 - OS: iOS14.8
 - Версия приложения 4.0.1

**Comment by ReanSn0w** [comment]
Проблема в том что смешаны кнопки и индикаторы. К примеру счётчик комментариев, это индикатор и действий не вызывает, а значке поделится это кнопка и обычно не нужно выделять акцентным цветом
