### ISSUE TITLE
Ошибка в момент публикации новости

### ISSUE THREAD

**Issue by DimaShul** [Ace-Place/bug-tracker#66]
**Описание бага**
В момент редактирования не получилось добавить новое фото, данная проблема не проходила каждый раз, но во время тестирования я пробовал несколько раз, через раз выплывала данная ошибка, не мог нажать на большой + чтобы добавить фото.

**Ожидаемое поведение (Опционально)**
По-моему мнению такая проблема не должна возникать на постоянном пользовании.

**Медиа (Опционально)**

https://user-images.githubusercontent.com/89010091/138753975-3354a458-dd18-4633-ac3b-e423c4ab3c5b.MP4

![BB814118-65ED-499A-9827-0D1AAB87CD2A](https://user-images.githubusercontent.com/89010091/138753990-4c582144-34c0-45d6-839c-de2b49832c27.jpeg)

Сведения об устройстве:
 - Устройство:  iPhone Хs max
 - OS: iOS14.8
 - Версия приложения 4.0.1

**Comment by ReanSn0w** [comment]
Воспроизвести не удалось, но на всякий случай сделал активной для нажатия всю область квадрата
