### ISSUE TITLE
Не нажимается кнопка коментов в открытом комментарии.

### ISSUE THREAD

**Issue by DimaShul** [Ace-Place/bug-tracker#68]
**Описание бага**
Кнопка поделиться нажимается, а коментов нет.

**Ожидаемое поведение (Опционально)**
Должна быть возможность нажимать на обе кнопки.

**Медиа (Опционально)**

https://user-images.githubusercontent.com/89010091/138922868-7822e838-e955-4ccf-b2f1-542a9e833758.MP4

![B50DB4B4-8DE2-487D-809B-7094FE474611](https://user-images.githubusercontent.com/89010091/138922896-ab1192de-72dc-405e-9254-d9cdd31ea0ad.jpeg)

Сведения об устройстве:
 - Устройство:  iPhone Хs max
 - OS: iOS14.8
 - Версия приложения 4.0.1

**Comment by ReanSn0w** [comment]
dublicate #65
