### ISSUE TITLE
Ошибка в редактировании поста в новостях

### ISSUE THREAD

**Issue by DimaShul** [Ace-Place/bug-tracker#69]
**Описание бага**
Проблема как в публикации фото, так и в редактировании содержимого текста, я пытался добавить фото, добавляются лишь два, затем ждал долгое время фото не прогружались и нажимая на нижний ряд больших + не было никакой реакции.

**Ожидаемое поведение (Опционально)**
Не должно быть подобных ситуаций как на видео, должна быть возможность редактировать и публиковать фото, менять их и тд.

**Медиа (Опционально)**
Отправил в лс тг.

Сведения об устройстве:
 - Устройство:  iPhone Хs max
 - OS: iOS14.8
 - Версия приложения 4.0.1

**Comment by ReanSn0w** [comment]
При обновлении новости метка обновления документа остается неизменной / либо сбрасывается на 0. По-этому приложение не считает нужным обновлять контент новости
